name: coastsentinel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  cloud_firestore: 5.6.12
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  firebase_storage: 12.4.10
  exif: ^3.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_gen: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"          # Background color
  image: assets/logo.png    # Your splash logo
  android: true
  ios: true
